services:
  aurral:
    image: ghcr.io/lklynet/aurral:1.76.50
    container_name: aurral
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /srv/docker/aurral/data:/app/backend/data
      - /mnt/media/music/_aurral_weeklyflow:/data/weeklyflow
    networks:
      - mediahub_internal

networks:
  mediahub_internal:
    external: true