services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    dns:
      - 192.168.0.21
    environment:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/caddy-root.crt
    volumes:
      - /mnt/media/audiobooks/bookshelf:/audiobooks
      - /mnt/media/podcasts:/podcasts
      - /srv/docker/audiobookshelf/config:/config
      - /srv/docker/audiobookshelf/metadata:/metadata
      - /srv/docker/caddy/caddy-root.crt:/etc/ssl/certs/caddy-root.crt:ro
    restart: unless-stopped
    networks:
      - mediahub_internal

networks:
  mediahub_internal:
    external: true